In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [96]:
df = pd.read_csv("../data/processed/bundesliga_2010_2026.csv")

print(f"Anzahl Spiele: {len(df)}")
print(f"Anzahl Spalten: {len(df.columns)}")

Anzahl Spiele: 4896
Anzahl Spalten: 195

In [97]:
df.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,D1,20/08/10,Bayern Munich,Wolfsburg,2,1,H,1.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,D1,21/08/10,FC Koln,Kaiserslautern,1,3,A,1.0,0.0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,D1,21/08/10,Freiburg,St Pauli,1,3,A,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,D1,21/08/10,Hamburg,Schalke 04,2,1,H,0.0,0.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,D1,21/08/10,Hannover,Ein Frankfurt,2,1,H,1.0,1.0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
df.tail()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
4891,D1,16/05/2026,Leverkusen,Hamburg,1,1,D,0.0,0.0,D,...,7.50,1.25,6.5,9.50,1.30,6.5,8.00,1.3,6.0,8.00
4892,D1,16/05/2026,M'gladbach,Hoffenheim,4,0,H,2.0,0.0,H,...,1.58,4.60,4.5,1.60,4.33,4.4,1.67,4.2,4.4,1.67
4893,D1,16/05/2026,St Pauli,Wolfsburg,1,3,A,0.0,1.0,A,...,2.35,2.55,3.6,2.55,2.60,3.5,2.60,2.6,3.5,2.60
4894,D1,16/05/2026,Union Berlin,Augsburg,4,0,H,2.0,0.0,H,...,2.25,2.50,4.0,2.40,2.50,4.0,2.40,2.5,4.0,2.40
4895,D1,16/05/2026,Werder Bremen,Dortmund,0,2,A,0.0,0.0,D,...,1.91,3.10,4.0,2.05,3.00,4.0,2.10,3.0,4.0,2.10

In [99]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4896 entries, 0 to 4895
Columns: 195 entries, Div to LBCA
dtypes: float64(185), int64(2), str(8)
memory usage: 7.3 MB

In [100]:
df.columns.tolist()

['Div',
 'Date',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'GBH',
 'GBD',
 'GBA',
 'IWH',
 'IWD',
 'IWA',
 'LBH',
 'LBD',
 'LBA',
 'SBH',
 'SBD',
 'SBA',
 'WHH',
 'WHD',
 'WHA',
 'SJH',
 'SJD',
 'SJA',
 'VCH',
 'VCD',
 'VCA',
 'BSH',
 'BSD',
 'BSA',
 'Bb1X2',
 'BbMxH',
 'BbAvH',
 'BbMxD',
 'BbAvD',
 'BbMxA',
 'BbAvA',
 'BbOU',
 'BbMx>2.5',
 'BbAv>2.5',
 'BbMx<2.5',
 'BbAv<2.5',
 'BbAH',
 'BbAHh',
 'BbMxAHH',
 'BbAvAHH',
 'BbMxAHA',
 'BbAvAHA',
 'Unnamed: 70',
 'Unnamed: 71',
 'Unnamed: 72',
 'Season',
 'PSH',
 'PSD',
 'PSA',
 'PSCH',
 'PSCD',
 'PSCA',
 'Time',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'B365>2.5',
 'B365<2.5',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'AHh',
 'B365AHH',
 'B365AHA',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'B365CH',
 'B365CD',
 'B365CA',
 'BWCH',
 'BWCD',
 'BWCA',
 'IWCH',
 'IWCD',
 'IWCA',
 'WHCH',
 'WHCD',
 'WHCA',
 'VCCH',
 'VCCD',
 'VCCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'B365C>2.5',
 'B365C<2.5',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'AHCh',
 'B365CAHH',
 'B365CAHA',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA',
 'BFH',
 'BFD',
 'BFA',
 '1XBH',
 '1XBD',
 '1XBA',
 'BFEH',
 'BFED',
 'BFEA',
 'BFE>2.5',
 'BFE<2.5',
 'BFEAHH',
 'BFEAHA',
 'BFCH',
 'BFCD',
 'BFCA',
 '1XBCH',
 '1XBCD',
 '1XBCA',
 'BFECH',
 'BFECD',
 'BFECA',
 'BFEC>2.5',
 'BFEC<2.5',
 'BFECAHH',
 'BFECAHA',
 'BFDH',
 'BFDD',
 'BFDA',
 'BMGMH',
 'BMGMD',
 'BMGMA',
 'BVH',
 'BVD',
 'BVA',
 'CLH',
 'CLD',
 'CLA',
 'BFDCH',
 'BFDCD',
 'BFDCA',
 'BMGMCH',
 'BMGMCD',
 'BMGMCA',
 'BVCH',
 'BVCD',
 'BVCA',
 'CLCH',
 'CLCD',
 'CLCA',
 'LBCH',
 'LBCD',
 'LBCA']

In [101]:
df[[
    "Date",
    "HomeTeam",
    "AwayTeam",
    "FTHG",
    "FTAG",
    "FTR"
]].head(10)

       Date        HomeTeam        AwayTeam  FTHG  FTAG FTR
0  20/08/10   Bayern Munich       Wolfsburg     2     1   H
1  21/08/10         FC Koln  Kaiserslautern     1     3   A
2  21/08/10        Freiburg        St Pauli     1     3   A
3  21/08/10         Hamburg      Schalke 04     2     1   H
4  21/08/10        Hannover   Ein Frankfurt     2     1   H
5  21/08/10      Hoffenheim   Werder Bremen     4     1   H
6  21/08/10      M'gladbach        Nurnberg     1     1   D
7  22/08/10        Dortmund      Leverkusen     0     2   A
8  22/08/10           Mainz       Stuttgart     2     0   H
9  27/08/10  Kaiserslautern   Bayern Munich     2     0   H

In [102]:
missing = df.isnull().sum()

missing[missing > 0].sort_values(ascending=False)

Unnamed: 72    4896
Unnamed: 70    4896
Unnamed: 71    4896
CLCD           4683
CLCA           4683
               ...
HR                1
AF                1
AC                1
HY                1
HTHG              1
Length: 184, dtype: int64

In [103]:
df["FTR"].value_counts()

FTR
H    2188
A    1511
D    1197
Name: count, dtype: int64

In [104]:
df["FTR"].value_counts(normalize=True) * 100

FTR
H    44.689542
A    30.861928
D    24.448529
Name: proportion, dtype: float64

In [105]:
df[["FTHG", "FTAG"]].describe()

              FTHG         FTAG
count  4896.000000  4896.000000
mean      1.688725     1.337623
std       1.385436     1.230271
min       0.000000     0.000000
25%       1.000000     0.000000
50%       1.000000     1.000000
75%       2.000000     2.000000
max       9.000000     8.000000

In [106]:
home_wins = (df["FTR"] == "H").sum()
draws = (df["FTR"] == "D").sum()
away_wins = (df["FTR"] == "A").sum()

total = len(df)

print(f"Heimsiege: {home_wins} ({home_wins / total * 100:.2f}%)")
print(f"Unentschieden: {draws} ({draws / total * 100:.2f}%)")
print(f"Auswärtssiege: {away_wins} ({away_wins / total * 100:.2f}%)")

Heimsiege: 2188 (44.69%)
Unentschieden: 1197 (24.45%)
Auswärtssiege: 1511 (30.86%)

In [107]:
print("Anzahl Duplikate:", df.duplicated().sum())

Anzahl Duplikate: 0

In [108]:
teams = sorted(
    set(df["HomeTeam"].unique()) |
    set(df["AwayTeam"].unique())
)

print("Anzahl Teams:", len(teams))
print(teams)

Anzahl Teams: 32
['Augsburg', 'Bayern Munich', 'Bielefeld', 'Bochum', 'Braunschweig', 'Darmstadt', 'Dortmund', 'Ein Frankfurt', 'FC Koln', 'Fortuna Dusseldorf', 'Freiburg', 'Greuther Furth', 'Hamburg', 'Hannover', 'Heidenheim', 'Hertha', 'Hoffenheim', 'Holstein Kiel', 'Ingolstadt', 'Kaiserslautern', 'Leverkusen', "M'gladbach", 'Mainz', 'Nurnberg', 'Paderborn', 'RB Leipzig', 'Schalke 04', 'St Pauli', 'Stuttgart', 'Union Berlin', 'Werder Bremen', 'Wolfsburg']

In [109]:
games_per_season = df["Season"].value_counts().sort_index()
games_per_season

Season
2010/11    306
2011/12    306
2012/13    306
2013/14    306
2014/15    306
2015/16    306
2016/17    306
2017/18    306
2018/19    306
2019/20    306
2020/21    306
2021/22    306
2022/23    306
2023/24    306
2024/25    306
2025/26    306
Name: count, dtype: int64

In [120]:
df["Date"] = pd.to_datetime(
    df["Date"],
    format="%d/%m/%y",
    errors="coerce"
)

df = df.sort_values("Date").reset_index(drop=True)

In [121]:
df[["Date", "HomeTeam", "AwayTeam", "FTR"]].head()

        Date       HomeTeam        AwayTeam FTR
0 2010-08-20  Bayern Munich       Wolfsburg   H
1 2010-08-21        FC Koln  Kaiserslautern   A
2 2010-08-21       Freiburg        St Pauli   A
3 2010-08-21        Hamburg      Schalke 04   H
4 2010-08-21       Hannover   Ein Frankfurt   H